### ISSUE TITLE
Annotation for example values

### ISSUE THREAD

**Issue by ralpha** [GREsau/schemars#31] opened 2020-05-18 20:15 UTC
Adding support for examples.

Currently strings will have an example of:
```json
[
  {
    "list_of_int": [
      0
    ],
    "id": 0,
    "name": "string",
    "full_name": "string"
  }
],
```
Where strings are always `"string"` and int is always `0`
If we add examples we can give some more info.

Maybe with a syntax like:
```rust
#[schemars(example = "This is the example string")]
```

Used like this:
```rust
#[derive(Serialize, Deserialize, JsonSchema)]
pub struct Version {
    #[schemars(example = "1.0.0")]
    pub code: String,
    #[schemars(example = "First release of our crate/application.")]
    pub description: String,
}
```

This will result in something like:
```json
{
  "code": "1.0.0",
  "description": "First release of our crate/application."
}
```

I don't know how this can also be done for int, but I think that is less of an issue.
For enums the first value is converted to string and that is used. So that does not have to change I think.

This issue is a repost of: https://github.com/GREsau/okapi/issues/11

**Comment by GREsau** [comment] 2020-06-11 21:18
Duplicate of https://github.com/GREsau/schemars/issues/23 which was implemented in schemars v0.7.6

**Closed by GREsau** 2020-06-11 21:18 UTC
