### ISSUE TITLE
bug(schemars_derive/docs): newlines get stripped in example blocks

### ISSUE THREAD

**Issue by DonIsaac** [GREsau/schemars#313] opened 2024-08-11 16:49 UTC
```rs
use schemars::JsonSchema;
use serde::Deserialize;

/// # Some Config
/// 
/// This config does some stuff.
///
/// # Example
///
/// ```jsonc
/// {
///   // use this config setting in a certain way
///   "foo": ["bar", "baz"],
/// }
/// ```
#[derive(Debug, Deserialize, Default, JSONSchema)]
pub struct Config {
    foo: Vec<String>
}
```

When rendered to a JSON schema, the code block in the schema's `description` field will be stripped, causing invalid JSONC to be rendered. It looks like other markdown in `description` has its whitespace preserved.

**Comment by GREsau** [comment] 2024-08-11 20:50
Duplicate of #38 / #120 / #129

Fortunately, this is now fixed in schemars [v1.0.0-alpha.3](https://github.com/GREsau/schemars/releases/tag/v1.0.0-alpha.3)

**Closed by GREsau** 2024-08-11 20:50 UTC
