### ISSUE TITLE
Add support for custom properties

### ISSUE THREAD

**Issue by pjankiewicz** [GREsau/schemars#81] opened 2021-04-21 17:34 UTC
Thank you for creating this crate. It is really amazing. One thing that we are missing is the ability to allow custom properties in schemas. We are using the schemas to generate forms in the frontend automatically via https://github.com/koumoul-dev/vuetify-jsonschema-form.

One of the fields that we need to fill is x-tag=switch to control the looks of the field in the form. I see that things like title, description are supported but not the ability to use a custom property (or am I missing it?).

What I propose is to add `custom_props` as a dynamic HashMap<String, String> that can be encoded like this

```
#[schemars(custom_props="a=1,b=2,c=3")]
```

that would be decoded to custom properties `{"a": "1", "b": "2", "c": "3"}`. It would allow encoding only String => String but still it would be very nice in my opinion.

What do you think about this? I could create a PR with functionality like this.

**Comment by GREsau** [comment] 2021-04-21 18:56
I think this is the same as https://github.com/GREsau/schemars/issues/50?

**Comment by pjankiewicz** [comment] 2021-04-21 19:17
@GREsau Yes, sorry I was looking for an issue for this and missed the one you are pointing to. What do you think about the implementation I suggested? Should I do it like I suggested or rather expression like in the other issue? It would be nice to handle a `HashMap<String, Any>` not sure how easy it would be.

**Comment by GREsau** [comment] 2021-04-25 20:43
Closing as duplicate of #50

**Closed by GREsau** 2021-04-25 20:43 UTC
